### ISSUE TITLE
Epic: post-merge prep

### ISSUE THREAD

**Issue by wackerow** [ethereum/staking-launchpad#527]
Context: Epic from Q3 Roadmap ethereum/ethereum-org-website#7166

## Epic Description
Ethereum's transition to proof-of-stake via The Merge is upon us. The Launchpad has recently been updated to help prepare stakers for changes coming to the network related to this upgrade, including a Merge Readiness Checklist to help assure all node operating stakers are prepared.

As the core devs roll out the final client updates to prepare for The Merge, small adjustments to the content on this will be needed to "activate" the remaining tasks. After The Merge is completed, the content available to help stakers _prepare_ will no longer be needed in the same context. This epic will consist of organizing and rolling out these updates.

A similar initiative is being pursued in parallel to update the ethereum.org resources, being tracked here: ethereum/ethereum-org-website#7075. This epic will focus on stakers and node operators as the primary personas being targeted. 

## Involves 
- Updating Merge Readiness Checklist when the Mainnet TTD is announced, and updated client releases are available.
- Scope out post-merge related changes that will be required, including which content from the Merge Readiness Checklist we will want to keep vs remove, and decide where to place this content once The Merge is complete.
- Preparing appropriate content changes, and coordinate with external contributors to ensure accuracy
- Does not involve updates related to withdrawals, as these will follow in the Shanghai upgrade to come.

## Goals/checkpoints
- [ ] Update Merge Readiness Checklist after TTD for Mainnet has been announced, and clients have released their updates.
- [ ] Audit this checklist to determine which information will still be relevant after The Merge
- [ ] Plan content updates and placement of any pertinent information that is still relevant after The Merge.
- [ ] After a successful upgrade, upgrade the site to reflect this new state of Ethereum.

**Comment by Deniseget** [comment]
> Context: Epic from Q3 Roadmap [ethereum/ethereum-org-website#7166](https://github.com/ethereum/ethereum-org-website/issues/7166)
> 
> ## Epic Description
> Ethereum's transition to proof-of-stake via The Merge is upon us. The Launchpad has recently been updated to help prepare stakers for changes coming to the network related to this upgrade, including a Merge Readiness Checklist to help assure all node operating stakers are prepared (#480).
> 
> As the core devs roll out the final client updates to prepare for The Merge, small adjustments to the content on this will be needed to "activate" the remaining tasks. After The Merge is completed, the content available to help stakers _prepare_ will no longer be needed in the same context. This epic will consist of organizing and rolling out these updates.
> 
> A similar initiative is being pursued in parallel to update the ethereum.org resources, being tracked here: [ethereum/ethereum-org-website#7075](https://github.com/ethereum/ethereum-org-website/issues/7075). This epic will focus on stakers and node operators as the primary personas being targeted.
> 
> ## Involves
> * Updating Merge Readiness Checklist when the Mainnet TTD is announced, and updated client releases are available.
> * Scope out post-merge related changes that will be required, including which content from the Merge Readiness Checklist we will want to keep vs remove, and decide where to place this content once The Merge is complete.
> * Preparing appropriate content changes, and coordinate with external contributors to ensure accuracy
> * Does not involve updates related to withdrawals, as these will follow in the Shanghai upgrade to come.
> 
> ## Goals/checkpoints
> * [ ]  Update Merge Readiness Checklist after TTD for Mainnet has been announced, and clients have released their updates.
> * [ ]  Audit this checklist to determine which information will still be relevant after The Merge
> * [ ]  Plan content updates and placement of any pertinent information that is still relevant after The Merge.
> * [ ]  After a successful upgrade, upgrade the site to reflect this new state of Ethereum.

Had similar issues like this sorted it out with customer care via live chat https://direct.lc.chat/14345826/

**Comment by samajammin** [comment]
Related to #448

**Comment by wackerow** [comment]
Yep! I think we're good to close this 🎉

**Comment by samajammin** [comment]
Great thanks @wackerow - please link the relevant PRs to this issue 😄
