### ISSUE TITLE
Nichebiche equals love

### ISSUE THREAD

**Issue by Nichebiche** [ethereum/staking-launchpad#698]
_Originally posted by @hwwhww in https://github.com/hwwhww/eth-research/pull/1_
```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/staking-launchpad/issues/555
- [ ] https://github.com/ethereum/staking-launchpad/pull/477
- [ ] https://github.com/ethereum/staking-launchpad/pull/697
- [ ] https://github.com/ethereum/staking-launchpad/pull/695
- [ ] https://github.com/ethereum/staking-launchpad/issues/696
- [ ] https://github.com/ethereum/staking-launchpad/issues/685
- [ ] https://github.com/ethereum/staking-launchpad/issues/686
- [ ] https://github.com/ethereum/staking-launchpad/pull/692
- [ ] https://github.com/ethereum/staking-launchpad/issues/694
- [ ] https://github.com/ethereum/staking-launchpad/pull/693
- [ ] https://github.com/ethereum/staking-launchpad/issues/439
- [ ] https://github.com/ethereum/staking-launchpad/issues/691
- [ ] https://github.com/ethereum/staking-launchpad/issues/690
- [ ] https://github.com/ethereum/staking-launchpad/pull/689
- [ ] https://github.com/ethereum/staking-launchpad/pull/688
- [ ] https://github.com/ethereum/staking-launchpad/pull/687
- [ ] https://github.com/ethereum/staking-launchpad/issues/680
- [ ] https://github.com/ethereum/staking-launchpad/pull/684
- [ ] https://github.com/ethereum/staking-launchpad/pull/682
- [ ] https://github.com/ethereum/staking-launchpad/pull/683
- [ ] https://github.com/ethereum/staking-launchpad/pull/667
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/staking-launchpad/issues/555
- [ ] https://github.com/ethereum/staking-launchpad/pull/477
- [ ] https://github.com/ethereum/staking-launchpad/pull/697
- [ ] https://github.com/ethereum/staking-launchpad/pull/695
- [ ] https://github.com/ethereum/staking-launchpad/issues/696
- [ ] https://github.com/ethereum/staking-launchpad/issues/685
```

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/staking-launchpad/issues/555
- [ ] https://github.com/ethereum/staking-launchpad/pull/477
- [ ] https://github.com/ethereum/staking-launchpad/pull/697
- [ ] https://github.com/ethereum/staking-launchpad/pull/695
- [ ] https://github.com/ethereum/staking-launchpad/issues/696
- [ ] https://github.com/ethereum/staking-launchpad/pull/692
- [ ] https://github.com/ethereum/staking-launchpad/issues/694
- [ ] https://github.com/ethereum/staking-launchpad/pull/693
- [ ] https://github.com/ethereum/staking-launchpad/issues/439
```
